# yaml-language-server: $schema=https://raw.githubusercontent.com/robertobarbedo/SiteKit/refs/heads/main/SiteKit.CLI/SiteKit/schemas/sitesettings-schema.json
site:
  name: $(name)
  default_language: "en"
  site_path: "$(site_path)"
  dictionary_path: "$(dictionary_path)"
  site_template_path: "$(site_template_path)"
  datasource_template_path: "$(datasource_template_path)"
  rendering_path: "$(rendering_path)"
  placeholder_path: "$(placeholder_path)"
  available_renderings_path: "$(available_renderings_path)"
  site_placeholder_path: "$(site_placeholder_path)"
  partial_designs_path: "$(partial_designs_path)"
  page_designs_path: "$(page_designs_path)"
  defaults:
    page_base_template: ""
    page_workflow: ""
    datasource_workflow: ""
    language_fallback: false


